version: '3.8'

networks:
  net:
    driver: bridge
    ipam: 
     driver: 
      default
     config:
       - subnet: 192.168.8.192/29 #192.168.8.193 - 192.168.8.194 
    driver_opts:
      com.docker.network.bridge.name: diaspora_net


services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=diaspora
      - POSTGRES_PASSWORD=diaspora
      - POSTGRES_DB=diaspora_production
    networks:
      - net
  
#  db:
#    container_name: db
#    image: 'yobasystems/alpine-mariadb:latest'
#    environment:
#      MYSQL_ROOT_PASSWORD: 'diaspora'
#      MYSQL_DATABASE: 'diaspora_production'
#      MYSQL_USER: 'diaspora'
#      MYSQL_PASSWORD: 'diaspora'
#    volumes:
#      - ./data/mysql:/var/lib/mysql
#    networks:
#      - net
#    restart: unless-stopped


  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    networks:
      - net

  diaspora:
    container_name: diaspora
    build: 
      context: .
      dockerfile: Dockerfile_diaspora
    environment:
      - RAILS_ENV=production
    depends_on:
      - db
      - redis
    volumes:
      - /home/diaspora/
      - /config/
    ports:
      - 8234:3000
    working_dir: /home/diaspora
    #command: run
    privileged: true
    networks: 
      - net

