postgres:
  build: database
  environment:
    - POSTGRES_USER=diaspora
    - POSTGRES_PASSWORD=diaspora
  volumes:
    - ../data/postgres/:/var/lib/postgresql

redis:
  build: redis

diaspora:
  build: diaspora
  links:
    - postgres
    - redis
  volumes:
    - ../data/diaspora:/home/diaspora
  expose:
    - "3000"
  working_dir: /home/diaspora
