# dbdata:
#   build: database
#   privileged: true
#   volumes:
#     - ../data/postgres/:/var/cache/postgres
#     - /var/lib/postgresql/data

postgres:
  image: postgres:9.4
  environment:
    - POSTGRES_USER=diaspora
    - POSTGRES_PASSWORD=diaspora
  # volumes_from:
  #   - dbdata

redis:
  build: redis

diaspora:
  build: diaspora
  links:
    - postgres
    - redis
  volumes:
    - home:/home
  expose:
    - "3000"
  working_dir: /home/diaspora
