dbdata:
  image: postgres:9.4
  command: /bin/true
  volumes:
    - /var/lib/postgresql/data

postgres:
  image: postgres:9.4
  environment:
    - POSTGRES_USER=diaspora
    - POSTGRES_PASSWORD=diaspora
  volumes_from:
    - dbdata
  command: postgres

diaspora:
  build: .
  links:
    - postgres
  volumes:
    - ../data/diaspora/uploads:/home/diaspora/diaspora/public/uploads
    - ../config/diaspora:/home/diaspora/diaspora/config
    - ../log/diaspora:/home/diaspora/diaspora/log
  expose:
    - "3000"
  working_dir: /home/diaspora
