postgres: &postgres
  adapter: postgresql
  host: postgres
  port: 5432
  username: diaspora
  password: diaspora
  encoding: unicode

# Comment the the mysql line and uncomment the postgres line
# if you want to use postgres
common: &common
  # Choose one of the following
  #<<: *mysql
  <<: *postgres

  # Should match environment.sidekiq.concurrency
  pool: 50

##################################################
#### CONFIGURE ABOVE #############################
##################################################

# Normally you don't need to touch anything here

postgres_travis: &postgres_travis
  adapter: postgresql
  username: postgres
combined: &combined
  <<: *common
development:
  <<: *combined
  database: diaspora_development
production:
  <<: *combined
  database: diaspora
test:
  <<: *combined
  database: "diaspora_test"
integration1:
  <<: *combined
  database: diaspora_integration1
integration2:
  <<: *combined
  database: diaspora_integration2
