FROM ubuntu:18.04


RUN apt-get update -y && apt-get install -y \
build-essential \
git \
curl \
gsfonts \
imagemagick \
libmagickwand-dev \
nodejs \
libssl-dev \
libcurl4-openssl-dev \
libxml2-dev \
libxslt1-dev 

#RUN apt-get update && apt-get upgrade -y && apt-get install -y cmake build-essential libgmp-dev libssl-dev libcurl4-openssl-dev libxml2-dev libxslt-dev imagemagick ghostscript git curl libpq-dev libmagickwand-dev nodejs gawk libreadline6-dev libyaml-dev libsqlite3-dev sqlite3 autoconf libgdbm-dev libncurses5-dev automake bison libffi-dev

RUN adduser --gecos "" --disabled-login --home /home/diaspora diaspora

RUN mkdir /home/diaspora/diaspora && chown diaspora:diaspora /home/diaspora/diaspora

RUN cd ~
RUN git clone -b master https://github.com/diaspora/diaspora.git
RUN cd diaspora

COPY run_as_diaspora.sh /run_as_diaspora.sh

COPY docker-entrypoint.sh /docker-entrypoint.sh

VOLUME /config

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["run"]
